-- LILICA -- MULTI-PERSON CARE CIRCLE INVITATION SCOPE (`\downloads\perm.txt`,
-- 15 September 2026).
--
-- REAL BUG THIS FIXES: davidmaruta2@gmail.com supports both Maggie and
-- Ben. He invited dtm35@cam.ac.uk once; dtm35 could see Maggie but not
-- Ben. Root cause (confirmed by inspecting the actual schema, not
-- inferred from UI labels): a care_space is exactly one supported
-- person (supported_people.care_space_id is UNIQUE); a membership is
-- exactly one (user, care_space) pair; and care_space_invitations.
-- care_space_id is a single not-null column -- ALL THREE are, and
-- remain, genuinely single-care-space primitives. invite_member()
-- therefore only ever created ONE invitation, scoped to Maggie's care
-- space alone -- Ben was simply never invited. This was not a bug in
-- accept_invitation()/RLS/domain grants; it was a missing UI/orchestration
-- capability: nothing let David select MULTIPLE supported people for one
-- invitation.
--
-- ARCHITECTURE CHOSEN (brief section 8, option A): a lightweight
-- "invitation bundle" that ORCHESTRATES the existing, completely
-- unmodified per-care-space primitives -- it does not replace them.
--   * care_space_invitation_groups: one row per organiser-facing
--     invitation ACTION covering 1+ explicitly-selected supported
--     people. Carries the ONE human-friendly invite_code and the ONE
--     set of server-authoritative delivery-state columns the invitee/
--     organiser actually experiences as "one invitation".
--   * care_space_invitations gains one additive, nullable
--     invitation_group_id column. NULL means "an ordinary,
--     ungrouped legacy invitation" -- its behaviour is completely
--     unchanged. Non-null means "one of this group's children" -- it
--     is still a real, independently-authoritative row: its own
--     care_space_id, its own role/domain grants, its own status. Its
--     own invite_code column is untouched (still NOT NULL, still
--     unique, still generated by generate_invitation_code()) but is
--     simply never shown to the user for a grouped invitation -- the
--     group's own invite_code is the one human-friendly code that
--     resolves the whole bundle.
--   * invite_member_group() creates/extends a group by calling the
--     EXISTING invite_member() once per selected care space (not a
--     reimplementation) -- so every authority check, idempotency
--     rule, and "this person already has access" rule invite_member()
--     already enforces applies IDENTICALLY per selected care space,
--     with zero duplicated logic. A care space where the invitee
--     already has active access is skipped (reported back as
--     'already_has_access', per brief sections 35/36) rather than
--     erroring the whole call; any OTHER failure (most importantly,
--     the organiser not actually being an active organiser of one of
--     the selected care spaces -- brief section 29) aborts the ENTIRE
--     call, and Postgres's own transactional rollback means nothing
--     partial is ever left behind.
--   * accept_invitation_group()/decline_invitation_group()/
--     revoke_invitation_group() each loop over the group's own pending
--     children calling the EXISTING accept_invitation()/
--     decline_invitation()/revoke_invitation() -- again, zero
--     duplicated membership/permission logic. Because none of these
--     three ever explicitly catches an exception, an uncaught failure
--     partway through rolls back EVERY child processed earlier in the
--     SAME call (natural Postgres transactional semantics) -- so
--     "Maggie accepted, Ben failed" can never be left half-done.
--   * resolve_invitation_by_code() (the already-corrected, single-
--     RPC, rate-limited resolver from
--     20260916170000_invitation_code_rate_limit_bypass_fix.sql) is
--     redefined ADDITIVELY: its authentication/rate-limit/threshold
--     logic is completely UNTOUCHED (preserved verbatim); it now also
--     checks care_space_invitation_groups.invite_code FIRST (a group
--     code can never collide with a legacy invitation's own internal
--     code -- see generate_invitation_group_code() below), and returns
--     every selected person's name plus a group_id the client uses to
--     call accept_invitation_group() instead of accept_invitation().
--   * list_my_invitations() and list_care_space_invitations() are
--     redefined additively to surface a group's full people list and
--     its own coherent delivery state, while every legacy, ungrouped
--     row continues to behave exactly as before.
--
-- WHAT THIS DOES NOT DO (brief sections 2/26/38, explicitly): no
-- global/account-wide Care Circle; no membership that spans more than
-- one care space; no rewrite of accept_invitation()/care_space_
-- memberships; no automatic access to a supported person added later;
-- Jackie (or anyone else not explicitly selected) never gains any
-- access, membership or visibility from this migration.

-- ---------------------------------------------------------------------
-- 1. The group table itself.
-- ---------------------------------------------------------------------
create table public.care_space_invitation_groups (
  id uuid primary key default gen_random_uuid(),
  invited_by_user_id uuid not null references auth.users(id) on delete restrict,
  invitee_email text not null,
  role text not null check (role in ('contributor', 'viewer')),
  relationship_type text not null default 'Someone else' check (
    relationship_type in ('Mum', 'Dad', 'Partner', 'Child', 'Grandparent', 'Other relative', 'Someone else')
  ),
  relationship_label text,
  constraint care_space_invitation_groups_relationship_label check (
    case
      when relationship_type in ('Other relative', 'Someone else')
        then char_length(btrim(relationship_label)) between 1 and 50
      else relationship_label is null
    end
  ),
  invite_code text not null unique,
  constraint care_space_invitation_groups_invite_code_shape
    check (invite_code ~ '^[A-Z2-9]{8}$'),
  status text not null default 'pending' check (
    status in ('pending', 'accepted', 'declined', 'expired', 'revoked')
  ),
  operation_id uuid not null unique,
  created_at timestamptz not null default statement_timestamp(),
  responded_at timestamptz,
  -- Server-authoritative delivery state, at the GROUP level -- brief
  -- section 23: "the organiser sent ONE invitation to one human." One
  -- email/Share action for the whole group, never a per-child fan-out.
  last_email_sent_at timestamptz,
  email_send_count integer not null default 0,
  last_share_opened_at timestamptz
);

alter table public.care_space_invitation_groups enable row level security;
alter table public.care_space_invitation_groups force row level security;
-- Deliberately NO policies -- exactly like invitation_code_attempts and
-- exactly like the existing invitee-side of care_space_invitations
-- itself (list_my_invitations() already bypasses RLS via SECURITY
-- DEFINER for the invitee, who has no membership yet to scope RLS
-- against). Every legitimate read of this table, for organiser or
-- invitee, already goes through a SECURITY DEFINER function below --
-- this is never queried directly by any client.

-- ---------------------------------------------------------------------
-- 2. Additive link column on the existing, unmodified invitations
--    table. NULL = ordinary legacy invitation, completely unchanged.
-- ---------------------------------------------------------------------
alter table public.care_space_invitations
  add column invitation_group_id uuid references public.care_space_invitation_groups(id);

create index care_space_invitations_group_idx
  on public.care_space_invitations (invitation_group_id)
  where invitation_group_id is not null;

-- ---------------------------------------------------------------------
-- 3. Group code generator -- same alphabet/length/shape as
--    generate_invitation_code(), but checked against BOTH tables so a
--    group code and a (never user-facing) legacy invitation code can
--    never collide, even though only one of the two namespaces is ever
--    shown to a user.
-- ---------------------------------------------------------------------
create function public.generate_invitation_group_code()
returns text
language plpgsql
set search_path = ''
as $$
declare
  alphabet text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  candidate text;
  attempt int := 0;
begin
  loop
    candidate := '';
    for i in 1..8 loop
      candidate := candidate || substr(alphabet, (floor(random() * length(alphabet)) + 1)::int, 1);
    end loop;
    attempt := attempt + 1;
    exit when not exists (
      select 1 from public.care_space_invitation_groups where invite_code = candidate
    ) and not exists (
      select 1 from public.care_space_invitations where invite_code = candidate
    );
    if attempt > 20 then
      raise exception 'Could not generate a unique invitation code' using errcode = '55000';
    end if;
  end loop;
  return candidate;
end;
$$;

-- ---------------------------------------------------------------------
-- 4. invite_member_group(): the one new organiser-facing entry point.
--    Orchestrates the EXISTING invite_member() once per selected care
--    space -- see the migration header for the full reasoning.
-- ---------------------------------------------------------------------
create function public.invite_member_group(
  target_care_space_ids uuid[],
  invitee_email_input text,
  member_role text,
  granted_domains text[],
  member_relationship_type text,
  member_relationship_label text,
  operation_id uuid
)
returns table (
  group_id uuid,
  invite_code text,
  care_space_id uuid,
  supported_person_name text,
  outcome text,
  -- One representative child invitation id, for the client's join link
  -- (which needs SOME real invitation id to build lilica://invite/<id>
  -- -- functionally only ever a deep-link trigger, never a lookup key,
  -- but a real id is safer/less surprising than a placeholder).
  representative_invitation_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  existing_group_id uuid;
  resolved_group_id uuid;
  resolved_code text;
  target_id uuid;
  child_invitation public.care_space_invitations%rowtype;
  distinct_count integer;
  any_invited boolean := false;
begin
  if caller_id is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if target_care_space_ids is null or array_length(target_care_space_ids, 1) is null then
    raise exception 'Select at least one supported person' using errcode = '22023';
  end if;

  select count(distinct value) into distinct_count from unnest(target_care_space_ids) as value;
  if distinct_count <> array_length(target_care_space_ids, 1) then
    raise exception 'The same supported person was selected more than once' using errcode = '22023';
  end if;

  -- Idempotency, mirroring invite_member()'s own operation_id pattern --
  -- a retried client call with the same operation_id returns the same
  -- already-created group rather than creating a second one.
  select ig.id into existing_group_id
  from public.care_space_invitation_groups ig
  where ig.operation_id = invite_member_group.operation_id;

  if existing_group_id is not null then
    resolved_group_id := existing_group_id;
    select ig.invite_code into resolved_code from public.care_space_invitation_groups ig where ig.id = resolved_group_id;
  else
    resolved_code := public.generate_invitation_group_code();
    insert into public.care_space_invitation_groups (
      invited_by_user_id, invitee_email, role, relationship_type, relationship_label,
      invite_code, operation_id
    ) values (
      caller_id, lower(trim(invitee_email_input)), member_role, member_relationship_type, member_relationship_label,
      resolved_code, invite_member_group.operation_id
    )
    returning id into resolved_group_id;
  end if;

  foreach target_id in array target_care_space_ids loop
    begin
      -- Reuses invite_member() completely unmodified -- identical
      -- authority check (only an active organiser of THIS specific
      -- care space may invite for it -- brief section 29), identical
      -- validation, identical idempotent upsert-while-pending
      -- behaviour, identical "already has access" rejection (brief
      -- sections 35/36).
      child_invitation := public.invite_member(
        target_id, invitee_email_input, member_role, granted_domains,
        member_relationship_type, member_relationship_label, gen_random_uuid()
      );
      update public.care_space_invitations
      set invitation_group_id = resolved_group_id
      where id = child_invitation.id;
      any_invited := true;

      group_id := resolved_group_id;
      invite_code := resolved_code;
      care_space_id := target_id;
      select sp.display_name into supported_person_name from public.supported_people sp where sp.care_space_id = target_id;
      outcome := 'invited';
      representative_invitation_id := child_invitation.id;
      return next;
    exception
      when others then
        if sqlerrm = 'This person already has access to this care space' then
          group_id := resolved_group_id;
          invite_code := resolved_code;
          care_space_id := target_id;
          select sp.display_name into supported_person_name from public.supported_people sp where sp.care_space_id = target_id;
          outcome := 'already_has_access';
          representative_invitation_id := null;
          return next;
        else
          -- Any OTHER failure (wrong authority, invalid role, invalid
          -- email, etc.) aborts the ENTIRE call -- Postgres rolls back
          -- everything this call did, including the group row itself,
          -- so nothing partial is ever left behind (brief section 29:
          -- "server must reject unauthorised care-space inclusion").
          raise;
        end if;
    end;
  end loop;

  -- Nothing was actually invited (every selected person already has
  -- access) -- remove the now-pointless empty group rather than
  -- leaving an orphan row with zero children.
  if not any_invited then
    delete from public.care_space_invitation_groups where id = resolved_group_id;
    group_id := null;
    invite_code := null;
  end if;
end;
$$;

revoke all on function public.invite_member_group(uuid[], text, text, text[], text, text, uuid) from public;
revoke all on function public.invite_member_group(uuid[], text, text, text[], text, text, uuid) from anon;
grant execute on function public.invite_member_group(uuid[], text, text, text[], text, text, uuid) to authenticated;

-- ---------------------------------------------------------------------
-- 5. resolve_invitation_by_code(), redefined additively. The
--    authentication/rate-limit/threshold logic below is copied
--    VERBATIM from 20260916170000_invitation_code_rate_limit_bypass_
--    fix.sql -- completely preserved, not reworked -- with exactly one
--    addition: after normalising the code, it now checks
--    care_space_invitation_groups FIRST. A legacy invitation's own
--    invite_code and a group's invite_code can never collide (enforced
--    by generate_invitation_group_code() checking both tables), so
--    there is no ambiguity in trying the group table first.
-- ---------------------------------------------------------------------
drop function if exists public.resolve_invitation_by_code(text);

create function public.resolve_invitation_by_code(code_input text)
returns table (
  result_status text,
  id uuid,
  group_id uuid,
  care_space_name text,
  care_space_names text[],
  invited_by_display_name text,
  role text,
  granted_domains text[]
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  window_seconds constant int := 300;
  max_attempts constant int := 10;
  existing_attempt public.invitation_code_attempts%rowtype;
  throttled boolean := false;
  normalised_code text;
  invitation public.care_space_invitations%rowtype;
  found_group public.care_space_invitation_groups%rowtype;
  person_name text;
  inviter_name text;
  person_names text[];
  representative_invitation public.care_space_invitations%rowtype;
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  -- Rate-limit accounting -- UNCHANGED from the security-correction
  -- migration. Preserved verbatim: unconditional, before any lookup,
  -- and every business-level outcome below is RETURNED, never RAISEd,
  -- so nothing here is ever rolled back.
  select * into existing_attempt
  from public.invitation_code_attempts
  where user_id = (select auth.uid())
  for update;

  if not found then
    insert into public.invitation_code_attempts (user_id, window_start, attempt_count)
    values ((select auth.uid()), now(), 1);
  elsif existing_attempt.window_start <= now() - (window_seconds || ' seconds')::interval then
    update public.invitation_code_attempts
    set window_start = now(), attempt_count = 1
    where user_id = (select auth.uid());
  elsif existing_attempt.attempt_count >= max_attempts then
    throttled := true;
  else
    update public.invitation_code_attempts
    set attempt_count = attempt_count + 1
    where user_id = (select auth.uid());
  end if;

  if throttled then
    return query select 'throttled'::text, null::uuid, null::uuid, null::text, null::text[], null::text, null::text, null::text[];
    return;
  end if;

  normalised_code := upper(regexp_replace(coalesce(code_input, ''), '[^A-Za-z0-9]', '', 'g'));
  if normalised_code = '' then
    return query select 'invalid_input'::text, null::uuid, null::uuid, null::text, null::text[], null::text, null::text, null::text[];
    return;
  end if;

  -- Lazy expiry -- legacy single-person path, unchanged.
  update public.care_space_invitations inv
  set status = 'expired'
  where inv.invite_code = normalised_code
    and inv.status = 'pending'
    and inv.expires_at <= now();

  -- 5a. Try the GROUP table first.
  select * into found_group
  from public.care_space_invitation_groups
  where invite_code = normalised_code;

  if found then
    -- Lazy expiry for every child of this group -- the legacy sweep
    -- above only matches a row by its OWN (never user-facing)
    -- invite_code, which never equals the group's own code, so a
    -- group's children need their own explicit sweep here.
    update public.care_space_invitations child
    set status = 'expired'
    where child.invitation_group_id = found_group.id
      and child.status = 'pending'
      and child.expires_at <= now();

    -- Lazy group expiry -- coherent: if every pending child of this
    -- group has independently expired (each child's own expires_at
    -- comes from invite_member()'s own default/refresh logic, and every
    -- child was created/refreshed together in the same
    -- invite_member_group() call, so they share the same expiry), mark
    -- the group expired too rather than leaving it "pending" with
    -- nothing left to accept.
    if found_group.status = 'pending' and not exists (
      select 1 from public.care_space_invitations child
      where child.invitation_group_id = found_group.id and child.status = 'pending'
    ) then
      update public.care_space_invitation_groups grp set status = 'expired' where grp.id = found_group.id;
      found_group.status := 'expired';
    end if;

    if found_group.status <> 'pending' then
      return query select 'inactive'::text, null::uuid, null::uuid, null::text, null::text[], null::text, null::text, null::text[];
      return;
    end if;

    -- Ordered by name, not created_at -- every child of a group is
    -- created in the SAME invite_member_group() call, so their
    -- statement_timestamp()-derived created_at values can tie, which
    -- would make a created_at ordering non-deterministic. Alphabetical
    -- is both stable and a sensible display order.
    select array_agg(coalesce(sp.display_name, 'a Lilica care space') order by sp.display_name)
      into person_names
    from public.care_space_invitations ci
    join public.supported_people sp on sp.care_space_id = ci.care_space_id
    where ci.invitation_group_id = found_group.id and ci.status = 'pending';

    select * into representative_invitation
    from public.care_space_invitations
    where invitation_group_id = found_group.id and status = 'pending'
    order by created_at
    limit 1;

    select profile.display_name into inviter_name
    from public.care_space_memberships membership
    join public.profiles profile on profile.id = membership.user_id
    where membership.id = representative_invitation.invited_by_membership_id;

    return query
    select
      'ok'::text,
      representative_invitation.id,
      found_group.id,
      coalesce(person_names[1], 'a Lilica care space'),
      coalesce(person_names, '{}'),
      coalesce(inviter_name, 'The organiser'),
      representative_invitation.role,
      representative_invitation.granted_domains;
    return;
  end if;

  -- 5b. Legacy single-person path -- completely unchanged behaviour.
  select * into invitation
  from public.care_space_invitations
  where invite_code = normalised_code;

  if not found then
    return query select 'not_found'::text, null::uuid, null::uuid, null::text, null::text[], null::text, null::text, null::text[];
    return;
  end if;

  if invitation.status <> 'pending' then
    return query select 'inactive'::text, null::uuid, null::uuid, null::text, null::text[], null::text, null::text, null::text[];
    return;
  end if;

  select display_name into person_name
  from public.supported_people
  where care_space_id = invitation.care_space_id;

  select profile.display_name into inviter_name
  from public.care_space_memberships membership
  join public.profiles profile on profile.id = membership.user_id
  where membership.id = invitation.invited_by_membership_id;

  return query
  select
    'ok'::text,
    invitation.id,
    null::uuid,
    coalesce(person_name, 'a Lilica care space'),
    array[coalesce(person_name, 'a Lilica care space')],
    coalesce(inviter_name, 'The organiser'),
    invitation.role,
    invitation.granted_domains;
end;
$$;

revoke all on function public.resolve_invitation_by_code(text) from public;
revoke all on function public.resolve_invitation_by_code(text) from anon;
grant execute on function public.resolve_invitation_by_code(text) to authenticated;

-- ---------------------------------------------------------------------
-- 6. accept_invitation_group() / decline_invitation_group() /
--    revoke_invitation_group(): orchestrate the EXISTING accept_
--    invitation()/decline_invitation()/revoke_invitation() over every
--    still-pending child. None of these three catches an exception, so
--    Postgres's own transactional rollback makes each one naturally
--    atomic -- brief section 12's "all succeed or fail coherently,
--    never partial" requirement, with zero new transaction-control
--    code and zero duplicated membership/permission logic.
-- ---------------------------------------------------------------------
create function public.accept_invitation_group(target_group_id uuid, operation_id uuid)
returns uuid[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_email text;
  found_group public.care_space_invitation_groups%rowtype;
  child_id uuid;
  new_membership_id uuid;
  membership_ids uuid[] := '{}'::uuid[];
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select lower(email) into caller_email from auth.users where id = (select auth.uid());

  select * into found_group
  from public.care_space_invitation_groups
  where id = target_group_id
  for update;

  if not found or caller_email is null or lower(found_group.invitee_email) <> caller_email then
    raise exception 'Invitation not found' using errcode = '42501';
  end if;

  if found_group.status <> 'pending' then
    raise exception 'This invitation is no longer open' using errcode = '22023';
  end if;

  for child_id in
    select id from public.care_space_invitations
    where invitation_group_id = target_group_id and status = 'pending'
    order by created_at
  loop
    -- accept_invitation() itself derives a fresh, distinct membership id
    -- for a brand-new membership (its own gen_random_uuid()-equivalent
    -- via the passed operation_id) -- a distinct operation_id per child
    -- is required since care_space_memberships.id must be unique
    -- per-row; reusing the SAME id across children would collide.
    new_membership_id := public.accept_invitation(child_id, gen_random_uuid());
    membership_ids := membership_ids || new_membership_id;
  end loop;

  if array_length(membership_ids, 1) is null then
    -- Every child had already left the pending state some other way
    -- (e.g. independently revoked one-by-one) by the time this ran.
    raise exception 'This invitation is no longer open' using errcode = '22023';
  end if;

  update public.care_space_invitation_groups
  set status = 'accepted', responded_at = now()
  where id = target_group_id;

  return membership_ids;
end;
$$;

revoke all on function public.accept_invitation_group(uuid, uuid) from public;
revoke all on function public.accept_invitation_group(uuid, uuid) from anon;
grant execute on function public.accept_invitation_group(uuid, uuid) to authenticated;

create function public.decline_invitation_group(target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_email text;
  found_group public.care_space_invitation_groups%rowtype;
  child_id uuid;
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select lower(email) into caller_email from auth.users where id = (select auth.uid());

  select * into found_group
  from public.care_space_invitation_groups
  where id = target_group_id
  for update;

  if not found or caller_email is null or lower(found_group.invitee_email) <> caller_email then
    raise exception 'Invitation not found' using errcode = '42501';
  end if;

  if found_group.status <> 'pending' then
    raise exception 'This invitation is no longer open' using errcode = '22023';
  end if;

  for child_id in
    select id from public.care_space_invitations
    where invitation_group_id = target_group_id and status = 'pending'
  loop
    perform public.decline_invitation(child_id);
  end loop;

  update public.care_space_invitation_groups
  set status = 'declined', responded_at = now()
  where id = target_group_id;
end;
$$;

revoke all on function public.decline_invitation_group(uuid) from public;
revoke all on function public.decline_invitation_group(uuid) from anon;
grant execute on function public.decline_invitation_group(uuid) to authenticated;

create function public.revoke_invitation_group(target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  found_group public.care_space_invitation_groups%rowtype;
  child_id uuid;
  revoked_any boolean := false;
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select * into found_group
  from public.care_space_invitation_groups
  where id = target_group_id
  for update;

  if not found then
    raise exception 'Invitation not found' using errcode = '42501';
  end if;

  if found_group.status <> 'pending' then
    raise exception 'This invitation is no longer open' using errcode = '22023';
  end if;

  -- revoke_invitation() itself enforces "only an active organiser of
  -- THIS child's own care space" per child -- if the caller organises
  -- some but not all of the group's care spaces, this fails (and rolls
  -- back) rather than partially revoking, which is the same coherent-
  -- or-nothing guarantee brief section 19 asks for.
  for child_id in
    select id from public.care_space_invitations
    where invitation_group_id = target_group_id and status = 'pending'
  loop
    perform public.revoke_invitation(child_id);
    revoked_any := true;
  end loop;

  if not revoked_any then
    raise exception 'This invitation is no longer open' using errcode = '22023';
  end if;

  update public.care_space_invitation_groups
  set status = 'revoked', responded_at = now()
  where id = target_group_id;
end;
$$;

revoke all on function public.revoke_invitation_group(uuid) from public;
revoke all on function public.revoke_invitation_group(uuid) from anon;
grant execute on function public.revoke_invitation_group(uuid) to authenticated;

-- ---------------------------------------------------------------------
-- 7. Delivery-state recorders for a group -- exact mirror of
--    record_invitation_email_sent()/record_invitation_share_opened(),
--    keyed to the group instead of one child, and authorised by "an
--    active organiser of ANY of this group's own care spaces" (the
--    same person who could see/send any single child invitation).
-- ---------------------------------------------------------------------
create function public.record_invitation_group_email_sent(target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  update public.care_space_invitation_groups grp
  set last_email_sent_at = now(),
      email_send_count = grp.email_send_count + 1
  where grp.id = target_group_id
    and exists (
      select 1
      from public.care_space_invitations child
      join public.care_space_memberships organiser_membership
        on organiser_membership.care_space_id = child.care_space_id
      where child.invitation_group_id = grp.id
        and organiser_membership.user_id = (select auth.uid())
        and organiser_membership.role = 'organiser'
        and organiser_membership.membership_status = 'active'
    );

  if not found then
    raise exception 'Invitation not found' using errcode = '42501';
  end if;
end;
$$;

revoke all on function public.record_invitation_group_email_sent(uuid) from public;
revoke all on function public.record_invitation_group_email_sent(uuid) from anon;
grant execute on function public.record_invitation_group_email_sent(uuid) to authenticated;

create function public.record_invitation_group_share_opened(target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  update public.care_space_invitation_groups grp
  set last_share_opened_at = now()
  where grp.id = target_group_id
    and exists (
      select 1
      from public.care_space_invitations child
      join public.care_space_memberships organiser_membership
        on organiser_membership.care_space_id = child.care_space_id
      where child.invitation_group_id = grp.id
        and organiser_membership.user_id = (select auth.uid())
        and organiser_membership.role = 'organiser'
        and organiser_membership.membership_status = 'active'
    );

  if not found then
    raise exception 'Invitation not found' using errcode = '42501';
  end if;
end;
$$;

revoke all on function public.record_invitation_group_share_opened(uuid) from public;
revoke all on function public.record_invitation_group_share_opened(uuid) from anon;
grant execute on function public.record_invitation_group_share_opened(uuid) to authenticated;

-- get_invitation_group_invite_code(): care_space_invitation_groups has
-- deliberately ZERO RLS policies (like invitation_code_attempts), so
-- not even the organiser's own authenticated client -- including the
-- send-invitation-email Edge Function, which uses a user-scoped client,
-- never service-role -- can read the group's own invite_code directly.
-- Same organiser-of-any-child-care-space authority as the delivery-
-- state recorders above.
create function public.get_invitation_group_invite_code(target_group_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  result_code text;
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select grp.invite_code into result_code
  from public.care_space_invitation_groups grp
  where grp.id = target_group_id
    and exists (
      select 1
      from public.care_space_invitations child
      join public.care_space_memberships organiser_membership
        on organiser_membership.care_space_id = child.care_space_id
      where child.invitation_group_id = grp.id
        and organiser_membership.user_id = (select auth.uid())
        and organiser_membership.role = 'organiser'
        and organiser_membership.membership_status = 'active'
    );

  if result_code is null then
    raise exception 'Invitation not found' using errcode = '42501';
  end if;

  return result_code;
end;
$$;

revoke all on function public.get_invitation_group_invite_code(uuid) from public;
revoke all on function public.get_invitation_group_invite_code(uuid) from anon;
grant execute on function public.get_invitation_group_invite_code(uuid) to authenticated;

-- ---------------------------------------------------------------------
-- 8. list_my_invitations(), redefined additively. A legacy (ungrouped)
--    pending invitation returns EXACTLY as before (one row,
--    careSpaceNames a single-element array). A grouped invitation
--    collapses ALL of its still-pending children into ONE row -- the
--    invitee experiences this as ONE invitation, per brief section 11.
-- ---------------------------------------------------------------------
drop function if exists public.list_my_invitations();

create function public.list_my_invitations()
returns table (
  id uuid,
  group_id uuid,
  care_space_id uuid,
  care_space_name text,
  care_space_names text[],
  invited_by_display_name text,
  role text,
  relationship_type text,
  relationship_label text,
  granted_domains text[],
  created_at timestamptz,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_email text;
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select lower(auth_user.email) into caller_email
  from auth.users auth_user
  where auth_user.id = (select auth.uid());
  if caller_email is null then
    return;
  end if;

  update public.care_space_invitations invitation
  set status = 'expired'
  where lower(invitation.invitee_email) = caller_email
    and invitation.status = 'pending'
    and invitation.expires_at <= now();

  -- Legacy, ungrouped rows -- unchanged behaviour.
  return query
  select
    invitation.id,
    null::uuid,
    invitation.care_space_id,
    coalesce(person.display_name, 'A Lilica care space'),
    array[coalesce(person.display_name, 'A Lilica care space')],
    coalesce(inviter_profile.display_name, 'The organiser'),
    invitation.role,
    invitation.relationship_type,
    invitation.relationship_label,
    invitation.granted_domains,
    invitation.created_at,
    invitation.expires_at
  from public.care_space_invitations invitation
  left join public.supported_people person on person.care_space_id = invitation.care_space_id
  left join public.care_space_memberships inviter_membership
    on inviter_membership.id = invitation.invited_by_membership_id
  left join public.profiles inviter_profile on inviter_profile.id = inviter_membership.user_id
  where lower(invitation.invitee_email) = caller_email
    and invitation.status = 'pending'
    and invitation.invitation_group_id is null

  union all

  -- Grouped rows -- one row per group, aggregating every still-pending
  -- child's own supported-person name. Role/domains are identical
  -- across every child of a group by construction (brief sections
  -- 13/14), so a representative child's values are exact for the whole
  -- group.
  select
    representative.id,
    grp.id,
    representative.care_space_id,
    coalesce(names.first_name, 'A Lilica care space'),
    coalesce(names.all_names, '{}'),
    coalesce(inviter_profile.display_name, 'The organiser'),
    representative.role,
    representative.relationship_type,
    representative.relationship_label,
    representative.granted_domains,
    grp.created_at,
    representative.expires_at
  from public.care_space_invitation_groups grp
  join lateral (
    select ci.* from public.care_space_invitations ci
    where ci.invitation_group_id = grp.id and ci.status = 'pending'
    order by ci.created_at
    limit 1
  ) representative on true
  join lateral (
    -- Ordered by name, not created_at -- see resolve_invitation_by_code()'s
    -- matching comment: same-call sibling rows can tie on
    -- statement_timestamp(), so alphabetical is the deterministic choice.
    select
      array_agg(coalesce(sp.display_name, 'A Lilica care space') order by sp.display_name) as all_names,
      (array_agg(coalesce(sp.display_name, 'A Lilica care space') order by sp.display_name))[1] as first_name
    from public.care_space_invitations ci
    join public.supported_people sp on sp.care_space_id = ci.care_space_id
    where ci.invitation_group_id = grp.id and ci.status = 'pending'
  ) names on true
  left join public.care_space_memberships inviter_membership
    on inviter_membership.id = representative.invited_by_membership_id
  left join public.profiles inviter_profile on inviter_profile.id = inviter_membership.user_id
  where lower(grp.invitee_email) = caller_email
    and grp.status = 'pending'

  order by created_at desc;
end;
$$;

revoke all on function public.list_my_invitations() from public;
revoke all on function public.list_my_invitations() from anon;
grant execute on function public.list_my_invitations() to authenticated;

-- ---------------------------------------------------------------------
-- 9. list_care_space_invitations(), redefined additively. Still scoped
--    to ONE care space (an organiser viewing Maggie's Care Circle sees
--    exactly Maggie's own row) -- but a grouped row's delivery state
--    and group_participant_names now come from the shared GROUP,
--    coherently, never per-child (brief section 23).
-- ---------------------------------------------------------------------
drop function if exists public.list_care_space_invitations(uuid);

create function public.list_care_space_invitations(target_care_space_id uuid)
returns table (
  id uuid,
  invitee_email text,
  role text,
  relationship_type text,
  relationship_label text,
  granted_domains text[],
  status text,
  invite_code text,
  group_id uuid,
  group_participant_names text[],
  last_email_sent_at timestamptz,
  email_send_count integer,
  last_share_opened_at timestamptz,
  created_at timestamptz,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or auth.role() <> 'authenticated' then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.care_space_memberships membership
    where membership.care_space_id = target_care_space_id
      and membership.user_id = (select auth.uid())
      and membership.role = 'organiser'
      and membership.membership_status = 'active'
  ) then
    raise exception 'Only an active organiser can view invitations' using errcode = '42501';
  end if;

  return query
  select
    invitation.id, invitation.invitee_email, invitation.role,
    invitation.relationship_type, invitation.relationship_label,
    invitation.granted_domains, invitation.status,
    -- The GROUP's own invite_code for a grouped row, never the child's
    -- own internal one -- the child's invite_code column still exists
    -- (invite_member()'s own NOT NULL default fires regardless) but is
    -- never shown to a user: sharing it instead of the group's code
    -- would silently resolve to a single-person preview missing
    -- everyone else in the group, defeating the whole feature.
    coalesce(grp.invite_code, invitation.invite_code),
    invitation.invitation_group_id,
    case when invitation.invitation_group_id is not null then
      (select array_agg(coalesce(sp.display_name, 'A Lilica care space') order by sp.display_name)
       from public.care_space_invitations ci
       join public.supported_people sp on sp.care_space_id = ci.care_space_id
       where ci.invitation_group_id = invitation.invitation_group_id)
    else null end,
    coalesce(grp.last_email_sent_at, invitation.last_email_sent_at),
    coalesce(grp.email_send_count, invitation.email_send_count),
    coalesce(grp.last_share_opened_at, invitation.last_share_opened_at),
    invitation.created_at, invitation.expires_at
  from public.care_space_invitations invitation
  left join public.care_space_invitation_groups grp on grp.id = invitation.invitation_group_id
  where invitation.care_space_id = target_care_space_id
  order by invitation.created_at desc;
end;
$$;

revoke all on function public.list_care_space_invitations(uuid) from public;
revoke all on function public.list_care_space_invitations(uuid) from anon;
grant execute on function public.list_care_space_invitations(uuid) to authenticated;

comment on table public.care_space_invitation_groups is
  'Orchestrates 1+ existing, independently-authoritative care_space_invitations rows as ONE organiser-facing invitation action. Never a security boundary itself -- membership/permission truth remains entirely in care_space_invitations/care_space_memberships/care_space_domain_grants, unchanged.';
comment on column public.care_space_invitations.invitation_group_id is
  'NULL for an ordinary legacy single-person invitation (unchanged behaviour). Non-null groups this row with 1+ siblings created by the same invite_member_group() call -- still an independently valid, independently revocable/expirable row.';
